Ashraful_CoreProject/Models/Product.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Ashraful_CoreProject.Models
{
    public class Product
    {
        [Key]
        public int ProductID { get; set; }

        [Required]
        public string Title { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime EntryDate { get; set; }
        public string UrlImage { get; set; }

        [Required]
        public string Price { get; set; }
        [Required]
        public string Detail { get; set; }

        [NotMapped]
        public IFormFile ImageUrl { get; set; }
    }
}

Ashraful_CoreProject/Models/ProductAjax.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Ashraful_CoreProject.Models
{
    public class ProductAjax
    {
        [Key]
        [MaxLength(6)]
        public string Code { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]

        public string Description { get; set; }
        [Required]

        public string Category { get; set; }
        [Required]
        [DataType(DataType.Date)]



        public DateTime EntryDate { get; set; }
        [Required]

        public float Price { get; set; }
        [Required]

        public string ImageUrl { get; set; }
    }
}

Ashraful_CoreProject/Controllers/ProductAjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ashraful_CoreProject.Data;
using Ashraful_CoreProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Ashraful_CoreProject.Controllers
{
    public class ProductAjaxController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductAjaxController(ApplicationDbContext context)
        {
            this._context = context;

        }



        public IActionResult IndexAjax()
        {
            List<ProductAjax> products = _context.ProductAjaxes.ToList();
            return View(products);
        }



        #region "Ajax Function"

        [HttpPost]
        public IActionResult DeleteProduct(string id)
        {
            ProductAjax product = _context.ProductAjaxes.Where(p => p.Code == id).FirstOrDefault();
            _context.Entry(product).State = EntityState.Deleted;
            _context.SaveChanges();
            return Ok();
        }

        public IActionResult ViewProduct(string id)
        {
            ProductAjax product = _context.ProductAjaxes.Where(p => p.Code == id).FirstOrDefault();
            return PartialView("_detail", product);
        }

        public IActionResult EditProduct(string id)
        {
            ProductAjax product = _context.ProductAjaxes.Where(p => p.Code == id).FirstOrDefault();
            return PartialView("_Edit", product);
        }

        public IActionResult UpdateProduct(ProductAjax product)
        {
            _context.Attach(product);
            _context.Entry(product).State = EntityState.Modified;
            _context.SaveChanges();
            return PartialView("_Product", product);
        }

        public IActionResult CreateProduct()
        {
            ProductAjax prod = new ProductAjax();

            return PartialView("_Create", prod);
        }

        [HttpPost]

        public IActionResult SaveProduct(ProductAjax product)
        {

            

            _context.Add(product);
            _context.SaveChanges();
            return PartialView("_Product", product);
        }

        #endregion
    }
}

Ashraful_CoreProject/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Ashraful_CoreProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace Ashraful_CoreProject.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository db;
        private readonly IHostingEnvironment appEnvironment;

        //private ApplicationDbContext app;

        public ProductController(IProductRepository db, IHostingEnvironment appEnvironment)
        {
            this.db = db;
            this.appEnvironment = appEnvironment;

        }

        public IActionResult Index()
        {
            return View(db.GetAll());
        }

        [Authorize(Policy = "CreateRolePolicy")]


        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<ActionResult> Create(Product _product)
        {
            if (ModelState.IsValid)
            {
                string UrlImage = "";

                var files = HttpContext.Request.Form.Files;
                foreach (var Image in files)
                {
                    if (Image != null && Image.Length > 0)
                    {
                        var file = Image;

                        var uploads = Path.Combine(appEnvironment.WebRootPath, "images");
                        if (file.Length > 0)
                        {
                            var fileName = Guid.NewGuid().ToString().Replace("-", "") + file.FileName;
                            using (var fileStream = new FileStream(Path.Combine(uploads, fileName), FileMode.Create))
                            {
                                await file.CopyToAsync(fileStream);
                                UrlImage = fileName;

                            }

                        }
                    }
                }

                var data = new Product()
                {
                    Title = _product.Title,
                    EntryDate = _product.EntryDate,
                    UrlImage = UrlImage,
                    Price = _product.Price,
                    Detail = _product.Detail
                };

                db.Add(data);
                return RedirectToAction(nameof(Index));

            }

            return RedirectToAction("Index");
        }


        [Authorize(Policy = "EditRolePolicy")]

        public IActionResult Edit(int id)
        {
            return View(db.GetProduct(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]


        public async Task<ActionResult> Edit(int id, Product _product)
        {
            if (ModelState.IsValid)
            {
                string UrlImage = "";
                var files = HttpContext.Request.Form.Files;
                foreach (var Image in files)
                {
                    if (Image != null && Image.Length > 0)
                    {
                        var file = Image;

                        var uploads = Path.Combine(appEnvironment.WebRootPath, "images");
                        if (file.Length > 0)
                        {
                            var fileName = Guid.NewGuid().ToString().Replace("-", "") + file.FileName;
                            using (var fileStream = new FileStream(Path.Combine(uploads, fileName), FileMode.Create))
                            {
                                await file.CopyToAsync(fileStream);
                                UrlImage = fileName;
                            }

                        }
                    }
                }
                var data = db.GetProduct(id);
                data.Title = _product.Title;
                data.EntryDate = _product.EntryDate;
                data.Price = _product.Price;
                data.Detail = _product.Detail;
                data.UrlImage = UrlImage;

                db.Update(data);
                return RedirectToAction(nameof(Index));

            }
            return RedirectToAction("Index");
        }


        public IActionResult Details(int id)
        {
            return View(db.GetProduct(id));

        }

        [Authorize(Policy = "DeleteRolePolicy")]


        public IActionResult Delete(int id)
        {
            db.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Ashraful_CoreProject/Views/ProductAjax/IndexAjax.cshtml
@model IEnumerable<Ashraful_CoreProject.Models.ProductAjax>

@{
        ViewData["Title"] = "IndexAjax";
}

<div class="container invisible" style="top:10%;height:80%; position:absolute;" id="DivDetailView">

</div>

<div id="DivListView" class="container visible">


    <form asp-action="CreateProduct" data-ajax="true" data-ajax-update="#DivDetailView" data-ajax-success="ShowDetailForm()">
        <button type="submit" class="btn btn-success">Create</button>
    </form>
    <br />

    <table class="table table-bordered table-hover" id="TblLists">
        <thead>

            <tr>
                <th>
                    Image
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Code)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EntryDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>

                <th>Actions</th>
            </tr>

        </thead>
        <tbody>
            @foreach (var item in Model)
            {


                <tr id="TR_@item.Code">
                    <partial name="_Product" model="@item" />
                </tr>

            }
        </tbody>
    </table>
</div>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
    function deleteItem(form) {
        var removeItemEl = $(form);
        removeItemEl.closest("tr").remove();
    }

    function ShowDetailForm() {
        $("#DivDetailView").addClass("visible");
        $("#DivDetailView").removeClass("invisible");

        $("#DivListView").addClass("invisible");
        $("#DivListView").removeClass("visible");
        return;
    }

    function CloseDetailForm() {
        $("#DivDetailView").addClass("invisible");
        $("#DivDetailView").removeClass("visible");

        $("#DivListView").addClass("visible");
        $("#DivListView").removeClass("invisible");
        return;
    }

    function CreateRow(id) {
        var table = document.getElementById('TblLists');
        var rows = table.getElementsByTagName('tr');
        var rowOuterHtml = rows[rows.length - 1].outerHTML;

        table.innerHTML = table.innerHTML + rowOuterHtml;
        rows = table.getElementsByTagName('tr');

        var row = rows[rows.length - 1];
        row.id = id;
        var tds = row.getElementsByTagName('td');
        for (i = 0; i < tds.length; i++) {
            tds[i].innerHTML = '';
        }
        return true;

    }

    </script>

}

Ashraful_CoreProject/Views/ProductAjax/_Create.cshtml
@model Ashraful_CoreProject.Models.ProductAjax

@{
    string NewRowId = DateTime.Now.Hour.ToString() + "" + DateTime.Now.Minute.ToString() + "" + DateTime.Now.Second.ToString();
}

<div class="row">
    <div class="col-md-4">
        @*<form asp-action="Create">*@

        <form id="EditForm" asp-action="SaveProduct" asp-controller="ProductAjax" onsubmit="return CreateRow('TR_@NewRowId')" data-ajax="true" data-ajax-success="CloseDetailForm();" data-ajax-update="#TR_@NewRowId">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntryDate" class="control-label"></label>
                <input asp-for="EntryDate" class="form-control" />
                <span asp-validation-for="EntryDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" id="test" />
            </div>
        </form>
    </div>
</div>

@*<div>
        <a asp-action="Index">Back to List</a>
    </div>*@

<div class="mt-4 text-center">
    <a class="btn btn-primary" onclick="CloseDetailForm();">Back</a>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}



}

Ashraful_CoreProject/Views/ProductAjax/_Edit.cshtml
@model Ashraful_CoreProject.Models.ProductAjax

@{
    ViewData["Title"] = "Edit";
}


<div class="row">
    <div class="col-md-4">
        @*<form asp-action="Edit">*@

        <form id="EditForm" asp-action="UpdateProduct" asp-controller="ProductAjax" data-ajax="true" data-ajax-success="CloseDetailForm();" data-ajax-update="#TR_@Model.Code">


            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Code" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntryDate" class="control-label"></label>
                <input asp-for="EntryDate" class="form-control" />
                <span asp-validation-for="EntryDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label><br />
                <img src="@Model.ImageUrl" style="width:150px;height:200px;" />
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="mt-4 text-center">
    <a class="btn btn-primary" onclick="CloseDetailForm();">Back</a>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ashraful_CoreProject/Views/ProductAjax/_Product.cshtml
@model Ashraful_CoreProject.Models.ProductAjax

<td>
    <img src="@Model.ImageUrl" style="width:70px;height:70px;" />
    @*<img src="~/images/@Model.ImageUrl" width="80" height="80" />*@

</td>
<td>
    @Html.DisplayFor(modelItem => Model.Code)
</td>

<td>
    @Html.DisplayFor(modelItem => Model.Name)
</td>
<td>
    @Html.DisplayFor(modelItem => Model.Description)
</td>
<td>
    @Html.DisplayFor(modelItem => Model.Category)
</td>
<td>
    @Html.DisplayFor(modelItem => Model.EntryDate)
</td>
<td>
    @Html.DisplayFor(modelItem => Model.Price)
</td>

<td>
    <div class="btn-group">
        @*<a asp-action="Edit" asp-route-id="@Model.Code" class="btn btn-warning">Edit</a>*@


        <form asp-action="EditProduct" asp-route-id="@Model.Code" data-ajax="true" data-ajax-update="#DivDetailView" data-ajax-success="ShowDetailForm()">
            <button type="submit" class="btn btn-sm btn-warning ml-1">Edit</button>
        </form>


        <form asp-action="ViewProduct" asp-route-id="@Model.Code" data-ajax="true" data-ajax-update="#DivDetailView" data-ajax-success="ShowDetailForm()">
            <button type="submit" class="btn btn-sm btn-primary ml-1">Details</button>
        </form>


        <form asp-action="DeleteProduct" asp-route-id="@Model.Code" data-ajax="true" data-ajax-success="deleteItem(this)">
            <button type="submit" class="btn btn-danger btn-sm ml-1" onclick="return confirm('Delete Confirmation For product @Model.Code');">Delete</button>
        </form>

    </div>
</td>

Ashraful_CoreProject/Views/ProductAjax/_detail.cshtml
@model Ashraful_CoreProject.Models.ProductAjax

@{
    ViewData["Title"] = "Details";
}



<div>

    <div class="row">
        <dl class="col-8">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Category)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Category)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.EntryDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.EntryDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Price)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Price)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ImageUrl)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ImageUrl)
            </dd>
        </dl>

        <div class="col-4">
            <img src="@Model.ImageUrl" width="350" height="420" />
        </div>

    </div>

    <div class="mt-4 text-center">
        <a class="btn btn-primary" onclick="CloseDetailForm();">Back</a>
    </div>

</div>